### ISSUE TITLE
unable to resolve ember-cli-coffeescript's package.json

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/hash-for-dep#21]
https://github.com/kimroen/ember-cli-coffeescript/pull/95

```
uildingCannot find module '/workspace/node_modules/ember-cli-coffeescript/lib//package.json'
Error: Cannot find module '/workspace/node_modules/ember-cli-coffeescript/lib//package.json'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at pkg (/workspace/node_modules/ember-cli-coffeescript/node_modules/broccoli-persistent-filter/node_modules/hash-for-dep/lib/pkg.js:19:20)
  at statPathsFor (/workspace/node_modules/ember-cli-coffeescript/node_modules/broccoli-persistent-filter/node_modules/hash-for-
```

**Comment by johnnyshields** [comment]
The specific ref that causes this issue is:

johnnyshields/ember-cli-coffeescript/ab59e5434bc534e5dad428c7a4fa7f07cb1a041e

**Comment by kimroen** [comment]
From the other issue - I don't think there's an error here. I'll try to confirm later today: https://github.com/kimroen/ember-cli-coffeescript/pull/95#issuecomment-155377720

**Comment by stefanpenner** [comment]
Good catch
