### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by amelmuharemovic** [stefanpenner/hash-for-dep#49]
I ran into the following error while `ember build/test` on node version 5.6.0.

```
TypeError: this is not a typed array.
    at Function.from (native)
    at hashTree (....ember/node_modules/hash-for-dep/lib/hash-tree.js:54:57)
    at Function.ModuleEntry.locate (....ember/node_modules/hash-for-dep/lib/module-entry.js:201:85)
    at hashForDep (....ember/node_modules/hash-for-dep/index.js:66:35)
    at TemplateCompiler.Filter.cacheKey (....ember/node_modules/broccoli-persistent-filter/index.js:248:10)
    at Object.module.exports.cacheKey (....ember/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:22:16)
    at Object.module.exports.init (....ember/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:12:50)
    at Processor.init (....ember/node_modules/broccoli-persistent-filter/lib/processor.js:16:18)
    at TemplateCompiler.Filter [as constructor] (....ember/node_modules/broccoli-persistent-filter/index.js:100:18)
    at new TemplateCompiler (....ember/node_modules/ember-cli-htmlbars/index.js:20:10)
```

**Comment by stefanpenner** [comment]
which version of hash-for-dep are you using?

**Comment by amelmuharemovic** [comment]
It seems that `ember-cli-htmlbars`, which I use as dependency, is using 1.4.3 version of `hash-for-dep` where this error occurs. Before that, with `hash-for-dep` version 1.2.3, it worked fine.

**Comment by stefanpenner** [comment]
@amelmuharemovic I can replicate on node 5.6, I'll work on a fix after my next meeting.

**Comment by stefanpenner** [comment]
(you should likely upgrade your node version though, that isn't supported by node anymore...)
(but don't worry I'll try and fix)

**Comment by stefanpenner** [comment]
fixed released as v1.4.4 🎉

**Comment by stefanpenner** [comment]
Also adding node 5 to CI: https://github.com/stefanpenner/hash-for-dep/pull/51

Note: We are planning to do a major version bump soon, which will drop support for all unsupported versions of node. So upgrading is strongly recommended.

**Comment by dcombslinkedin** [comment]
Thanks for the fix, Stef! Yeah, that is most definitely an unexpected issue.

**Comment by amelmuharemovic** [comment]
Thanks for the fix, will do an upgrade as soon as possible.
